name: Update Paper Server

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft version (e.g. 1.21.6)'
        required: true
        type: string
      project:
        description: 'Project type (paper, waterfall, etc)'
        required: false
        default: 'paper'
        type: string

permissions:
  contents: write

jobs:
  download-paper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup variables
      id: vars
      run: |
        filename="paper-${{ github.event.inputs.minecraft_version }}.jar"
        echo "filename=$filename" >> $GITHUB_OUTPUT
        echo "filepath=paper/$filename" >> $GITHUB_OUTPUT

    - name: Get latest Paper build
      id: paper-api
      env:
        PROJECT: ${{ github.event.inputs.project }}
        VERSION: ${{ github.event.inputs.minecraft_version }}
        USER_AGENT: github-actions-paper-updater/1.0.0
      run: |
        # Проверка доступности версии
        version_check=$(curl -s -H "User-Agent: $USER_AGENT" \
          "https://fill.papermc.io/v3/projects/$PROJECT/versions/$VERSION/builds")
        
        if echo "$version_check" | jq -e '.error' > /dev/null; then
          error_msg=$(echo "$version_check" | jq -r '.error')
          echo "::error ::Version check failed: $error_msg"
          exit 1
        fi

        # Получение URL последнего стабильного билда
        build_data=$(curl -s -H "User-Agent: $USER_AGENT" \
          "https://fill.papermc.io/v3/projects/$PROJECT/versions/$VERSION/builds")
        
        paper_url=$(echo "$build_data" | jq -r \
          '.builds[-1] | .downloads.server.default.url')

        if [ "$paper_url" = "null" ] || [ -z "$paper_url" ]; then
          echo "::error ::No builds found for $PROJECT $VERSION"
          exit 1
        fi

        echo "url=$paper_url" >> $GITHUB_OUTPUT

    - name: Download PaperMC server
      run: |
        mkdir -p paper
        curl -sSL -o "${{ steps.vars.outputs.filepath }}" \
          "${{ steps.paper-api.outputs.url }}"

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add paper/
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "Update Paper to ${{ github.event.inputs.minecraft_version }}"
          git push
        fi